// Every Plugipay feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 139 feature routes of the Plugipay API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Delete account (DELETE /api/v1/account) */
  accountDelete(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("DELETE", `/api/v1/account`, query, all);
  }

  /** Delete a linked account (DELETE /api/v1/account/linked-accounts/{provider}) */
  accountDeleteLinkedAccounts(provider: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/linked-accounts/${encodeURIComponent(provider)}`, {}, undefined);
  }

  /** Create an email change (POST /api/v1/account/email-change) */
  accountEmailChange(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/email-change`, query, all);
  }

  /** List linked accounts (GET /api/v1/account/linked-accounts) */
  accountLinkedAccounts(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/linked-accounts`, {}, undefined);
  }

  /** List account (GET /api/v1/account) */
  accountList(): Promise<unknown> {
    return this.call("GET", `/api/v1/account`, {}, undefined);
  }

  /** List members (GET /api/v1/account/members) */
  accountMembers(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/members`, {}, undefined);
  }

  /** Create a password change (POST /api/v1/account/password-change) */
  accountPasswordChange(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/password-change`, query, all);
  }

  /** List sessions (GET /api/v1/account/sessions) */
  accountSessions(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/sessions`, {}, undefined);
  }

  /** Revoke a session (POST /api/v1/account/sessions/{id}/revoke) */
  accountSessionsRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/sessions/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Create a revoke all (POST /api/v1/account/sessions/revoke-all) */
  accountSessionsRevokeAll(): Promise<unknown> {
    return this.call("POST", `/api/v1/account/sessions/revoke-all`, {}, undefined);
  }

  /** Update account (PATCH /api/v1/account) */
  accountUpdate(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account`, query, all);
  }

  /** Create an onboarding (POST /api/v1/adapters/managed/onboarding) */
  adaptersCreateManagedOnboarding(input: { "email": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/adapters/managed/onboarding`, query, all);
  }

  /** List adapters (GET /api/v1/adapters) */
  adaptersList(): Promise<unknown> {
    return this.call("GET", `/api/v1/adapters`, {}, undefined);
  }

  /** List onboarding (GET /api/v1/adapters/managed/onboarding) */
  adaptersManagedOnboarding(): Promise<unknown> {
    return this.call("GET", `/api/v1/adapters/managed/onboarding`, {}, undefined);
  }

  /** Dev-only: bypass Xendit webhook to simulate KYB/capabilities changes on staging. (POST /api/v1/adapters/managed/onboarding/_simulate) */
  adaptersManagedOnboardingSimulate(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/adapters/managed/onboarding/_simulate`, query, all);
  }

  /** Set manual (PUT /api/v1/adapters/manual) */
  adaptersManual(input?: { "bankAccounts"?: unknown[]; "staticQrImageUrl"?: string; "instructions"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/adapters/manual`, query, all);
  }

  /** Set midtrans (PUT /api/v1/adapters/midtrans) */
  adaptersMidtrans(input: { "serverKey": string; "clientKey": string; "merchantId": string; "env"?: "sandbox" | "production"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/adapters/midtrans`, query, all);
  }

  /** Set paypal (PUT /api/v1/adapters/paypal) */
  adaptersPaypal(input: { "clientId": string; "secret": string; "mode"?: "live" | "sandbox"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/adapters/paypal`, query, all);
  }

  /** Set xendit (PUT /api/v1/adapters/xendit) */
  adaptersXendit(input: { "secretKey": string; "callbackToken"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/adapters/xendit`, query, all);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input?: { "environment"?: unknown; "name"?: unknown; "scopes"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Delete an api key (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** Create a cancel (POST /api/v1/billing/cancel) */
  billingCancel(): Promise<unknown> {
    return this.call("POST", `/api/v1/billing/cancel`, {}, undefined);
  }

  /** Create a checkout (POST /api/v1/billing/checkout) */
  billingCheckout(input?: { "currency"?: unknown; "tier"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** List plans (GET /api/v1/billing/plans) */
  billingPlans(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plans`, {}, undefined);
  }

  /** List summary (GET /api/v1/billing/summary) */
  billingSummary(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/summary`, {}, undefined);
  }

  /** The account's own Plugipay plan (summary, upgrade, cancel): a signed-in person, or a key acting as its account. (GET /api/v1/billing/tiers) */
  billingTiers(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/tiers`, {}, undefined);
  }

  /** Bust the in-process cache. (POST /api/v1/billing/tiers/refresh) */
  billingTiersRefresh(): Promise<unknown> {
    return this.call("POST", `/api/v1/billing/tiers/refresh`, {}, undefined);
  }

  /** Returns settings + capability-derived availability (GET /api/v1/checkout/settings) */
  checkoutSettings(): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout/settings`, {}, undefined);
  }

  /** Partial update (PATCH /api/v1/checkout/settings) */
  checkoutUpdateSettings(input?: { "enabledMethods"?: unknown[]; "methodOrder"?: unknown[]; "methodAdapter"?: Record<string, unknown>; "brandName"?: string; "brandLogoUrl"?: string; "brandAccentColor"?: string; "brandTagline"?: string; "businessPhone"?: string; "businessEmail"?: unknown; "businessAddress"?: string; "businessTaxId"?: string; "receiptTemplate"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/checkout/settings`, query, all);
  }

  /** Cancel a checkout session (POST /api/v1/checkout-sessions/{id}/cancel) */
  checkoutSessionsCancel(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Merchant-side confirmation for manual (pending_review) sessions — the merchant has eyeballed the bank transfer / cash receipt / EDC slip and says "yes, money received". (POST /api/v1/checkout-sessions/{id}/confirm) */
  checkoutSessionsConfirm(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/confirm`, {}, undefined);
  }

  /** Create a checkout session (POST /api/v1/checkout-sessions) */
  checkoutSessionsCreate(input: { "amount": number; "currency": string; "customerId"?: string; "methods": unknown[]; "lineItems"?: unknown[]; "successUrl": string; "cancelUrl": string; "expiresInSec"?: number; "metadata"?: Record<string, unknown>; "templateId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/checkout-sessions`, query, all);
  }

  /** Delete a checkout session (DELETE /api/v1/checkout-sessions/{id}) */
  checkoutSessionsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/checkout-sessions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a checkout session (GET /api/v1/checkout-sessions/{id}) */
  checkoutSessionsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List checkout sessions (GET /api/v1/checkout-sessions) */
  checkoutSessionsList(input?: { "createdAfter"?: unknown; "createdBefore"?: unknown; "cursor"?: unknown; "customerId"?: unknown; "limit"?: unknown; "order"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["createdAfter"] = all["createdAfter"]; delete all["createdAfter"];
    query["createdBefore"] = all["createdBefore"]; delete all["createdBefore"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/checkout-sessions`, query, undefined);
  }

  /** Receipts — JSON DTO, PDF, thermal ESC/POS, and on-demand email. (GET /api/v1/checkout-sessions/{id}/receipt) */
  checkoutSessionsReceipt(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt`, {}, undefined);
  }

  /** Re-send / initial-send receipt via email. (POST /api/v1/checkout-sessions/{id}/receipt/email) */
  checkoutSessionsReceiptEmail(id: string, input?: { "to"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt/email`, query, all);
  }

  /** Receipt link lookup — given a session id, return the Receipt row that was auto-issued on completion. 404 before completion; 404 too for very old sessions that pre-date the Receipt table unless a backf (GET /api/v1/checkout-sessions/{id}/receipt-link) */
  checkoutSessionsReceiptLink(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt-link`, {}, undefined);
  }

  /** List receipt.escpos (GET /api/v1/checkout-sessions/{id}/receipt.escpos) */
  checkoutSessionsReceiptEscpos(id: string, input?: { "width"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["width"] = all["width"]; delete all["width"];
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt.escpos`, query, undefined);
  }

  /** Render a rich HTML receipt page. (GET /api/v1/checkout-sessions/{id}/receipt.html) */
  checkoutSessionsReceiptHtml(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt.html`, {}, undefined);
  }

  /** List receipt.pdf (GET /api/v1/checkout-sessions/{id}/receipt.pdf) */
  checkoutSessionsReceiptPdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/checkout-sessions/${encodeURIComponent(id)}/receipt.pdf`, {}, undefined);
  }

  /** Public runtime config — no auth, like /health. (GET /api/v1/config) */
  configList(): Promise<unknown> {
    return this.call("GET", `/api/v1/config`, {}, undefined);
  }

  /** Create a customer (POST /api/v1/customers) */
  customersCreate(input?: { "externalId"?: string; "email"?: string; "name"?: string; "phone"?: string; "taxId"?: string; "defaultPaymentTokenId"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/customers`, query, all);
  }

  /** Delete a customer (DELETE /api/v1/customers/{id}) */
  customersDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/customers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a customer (GET /api/v1/customers/{id}) */
  customersGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/customers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List customers (GET /api/v1/customers) */
  customersList(input?: { "createdAfter"?: unknown; "cursor"?: unknown; "email"?: unknown; "externalId"?: unknown; "limit"?: unknown; "order"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["createdAfter"] = all["createdAfter"]; delete all["createdAfter"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["email"] = all["email"]; delete all["email"];
    query["externalId"] = all["externalId"]; delete all["externalId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    return this.call("GET", `/api/v1/customers`, query, undefined);
  }

  /** Update a customer (PATCH /api/v1/customers/{id}) */
  customersUpdate(id: string, input?: { "externalId"?: string; "email"?: string; "name"?: string; "phone"?: string; "taxId"?: string; "defaultPaymentTokenId"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/customers/${encodeURIComponent(id)}`, query, all);
  }

  /** List metrics (GET /api/v1/dashboard/metrics) */
  dashboardMetrics(input?: { "window"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["window"] = all["window"]; delete all["window"];
    return this.call("GET", `/api/v1/dashboard/metrics`, query, undefined);
  }

  /** List overview (GET /api/v1/dashboard/overview) */
  dashboardOverview(): Promise<unknown> {
    return this.call("GET", `/api/v1/dashboard/overview`, {}, undefined);
  }

  /** Get an event (GET /api/v1/events/{id}) */
  eventsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/events/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List events (GET /api/v1/events) */
  eventsList(input?: { "cursor"?: unknown; "limit"?: unknown; "occurredAfter"?: unknown; "occurredBefore"?: unknown; "order"?: unknown; "type"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["occurredAfter"] = all["occurredAfter"]; delete all["occurredAfter"];
    query["occurredBefore"] = all["occurredBefore"]; delete all["occurredBefore"];
    query["order"] = all["order"]; delete all["order"];
    query["type"] = all["type"]; delete all["type"];
    return this.call("GET", `/api/v1/events`, query, undefined);
  }

  /** Create a replay (POST /api/v1/events/replay) */
  eventsReplay(input: { "eventIds": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/events/replay`, query, all);
  }

  /** Create a trigger (POST /api/v1/events/trigger) */
  eventsTrigger(input: { "type": string; "aggregateId": string; "data"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/events/trigger`, query, all);
  }

  /** Issue a gift card / store credit (store credit when customerId set) (POST /api/v1/gift-cards) */
  giftCardsCreate(input: { "amount": number; "currency"?: string; "customerId"?: string; "code"?: string; "expiresAt"?: string; "note"?: string; "issuedSource"?: string; "issuedRef"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/gift-cards`, query, all);
  }

  /** Balance lookup by redemption code (GET /api/v1/gift-cards/{code}) */
  giftCardsGet(code: string): Promise<unknown> {
    return this.call("GET", `/api/v1/gift-cards/${encodeURIComponent(code)}`, {}, undefined);
  }

  /** List (paginated, ?customerId= / ?status=) (GET /api/v1/gift-cards) */
  giftCardsList(input?: { "cursor"?: unknown; "customerId"?: unknown; "limit"?: unknown; "order"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/gift-cards`, query, undefined);
  }

  /** Use the card as tender (idempotent on externalRef) (POST /api/v1/gift-cards/{id}/redeem) */
  giftCardsRedeem(id: string, input: { "amount": number; "externalSource": string; "externalRef": string; "checkoutSessionId"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/gift-cards/${encodeURIComponent(id)}/redeem`, query, all);
  }

  /** Add value (e.g. refund → store credit) (POST /api/v1/gift-cards/{id}/topup) */
  giftCardsTopup(id: string, input: { "amount": number; "externalSource": string; "externalRef": string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/gift-cards/${encodeURIComponent(id)}/topup`, query, all);
  }

  /** Write off remaining balance (POST /api/v1/gift-cards/{id}/void) */
  giftCardsVoid(id: string, input?: { "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/gift-cards/${encodeURIComponent(id)}/void`, query, all);
  }

  /** Create an invoice (POST /api/v1/invoices) */
  invoicesCreate(input: { "customerId": string; "currency": string; "lines": unknown[]; "discount"?: number; "tax"?: number; "dueAt"?: string; "status"?: "draft" | "open"; "memo"?: string; "subscriptionId"?: string; "templateId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices`, query, all);
  }

  /** Finalize an invoice (POST /api/v1/invoices/{id}/finalize) */
  invoicesFinalize(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices/${encodeURIComponent(id)}/finalize`, query, all);
  }

  /** Get an invoice (GET /api/v1/invoices/{id}) */
  invoicesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List invoice.escpos (GET /api/v1/invoices/{id}/invoice.escpos) */
  invoicesInvoiceEscpos(id: string, input?: { "width"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["width"] = all["width"]; delete all["width"];
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}/invoice.escpos`, query, undefined);
  }

  /** List invoice.html (GET /api/v1/invoices/{id}/invoice.html) */
  invoicesInvoiceHtml(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}/invoice.html`, {}, undefined);
  }

  /** Invoice share / reprint — works for any status. (GET /api/v1/invoices/{id}/invoice.pdf) */
  invoicesInvoicePdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}/invoice.pdf`, {}, undefined);
  }

  /** List invoices (GET /api/v1/invoices) */
  invoicesList(input?: { "cursor"?: unknown; "customerId"?: unknown; "limit"?: unknown; "order"?: unknown; "status"?: unknown; "subscriptionId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["status"] = all["status"]; delete all["status"];
    query["subscriptionId"] = all["subscriptionId"]; delete all["subscriptionId"];
    return this.call("GET", `/api/v1/invoices`, query, undefined);
  }

  /** Pay an invoice (POST /api/v1/invoices/{id}/pay) */
  invoicesPay(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices/${encodeURIComponent(id)}/pay`, query, all);
  }

  /** List pdf (GET /api/v1/invoices/{id}/pdf) */
  invoicesPdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}/pdf`, {}, undefined);
  }

  /** Invoice → receipt lookup. (GET /api/v1/invoices/{id}/receipt) */
  invoicesReceipt(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/invoices/${encodeURIComponent(id)}/receipt`, {}, undefined);
  }

  /** Send an invoice (POST /api/v1/invoices/{id}/send) */
  invoicesSend(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices/${encodeURIComponent(id)}/send`, query, all);
  }

  /** Send email an invoice (POST /api/v1/invoices/{id}/send-email) */
  invoicesSendEmail(id: string, input?: { "to"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices/${encodeURIComponent(id)}/send-email`, query, all);
  }

  /** Void an invoice (POST /api/v1/invoices/{id}/void) */
  invoicesVoid(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/invoices/${encodeURIComponent(id)}/void`, query, all);
  }

  /** List balances (GET /api/v1/ledger/balances) */
  ledgerBalances(): Promise<unknown> {
    return this.call("GET", `/api/v1/ledger/balances`, {}, undefined);
  }

  /** List ledger (GET /api/v1/ledger) */
  ledgerList(input?: { "code"?: unknown; "cursor"?: unknown; "limit"?: unknown; "order"?: unknown; "sourceId"?: unknown; "sourceType"?: unknown; "txId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["code"] = all["code"]; delete all["code"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["sourceId"] = all["sourceId"]; delete all["sourceId"];
    query["sourceType"] = all["sourceType"]; delete all["sourceType"];
    query["txId"] = all["txId"]; delete all["txId"];
    return this.call("GET", `/api/v1/ledger`, query, undefined);
  }

  /** Managed Idempotent at the service layer (provisionSubAccount returns the existing sub-account id on a second call), so no request-level idempotency cache is needed. (POST /api/v1/onboarding/provision-managed) */
  onboardingProvisionManaged(): Promise<unknown> {
    return this.call("POST", `/api/v1/onboarding/provision-managed`, {}, undefined);
  }

  /** List balance (GET /api/v1/payouts/balance) */
  payoutsBalance(): Promise<unknown> {
    return this.call("GET", `/api/v1/payouts/balance`, {}, undefined);
  }

  /** List bank account (GET /api/v1/payouts/bank-account) */
  payoutsBankAccount(): Promise<unknown> {
    return this.call("GET", `/api/v1/payouts/bank-account`, {}, undefined);
  }

  /** Cancel a payout (POST /api/v1/payouts/{id}/cancel) */
  payoutsCancel(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payouts/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Create a payout (POST /api/v1/payouts) */
  payoutsCreate(input: { "amount": number; "currency": string; "bankCode"?: string; "bankName"?: string; "bankAccountNumber"?: string; "bankAccountHolder"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payouts`, query, all);
  }

  /** Get a payout (GET /api/v1/payouts/{id}) */
  payoutsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payouts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List payouts (GET /api/v1/payouts) */
  payoutsList(input?: { "cursor"?: unknown; "limit"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/payouts`, query, undefined);
  }

  /** Mark failed a payout (POST /api/v1/payouts/{id}/mark-failed) */
  payoutsMarkFailed(id: string, input: { "failureReason": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payouts/${encodeURIComponent(id)}/mark-failed`, query, all);
  }

  /** Mark in transit a payout (POST /api/v1/payouts/{id}/mark-in-transit) */
  payoutsMarkInTransit(id: string, input?: { "reference"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payouts/${encodeURIComponent(id)}/mark-in-transit`, query, all);
  }

  /** Mark paid a payout (POST /api/v1/payouts/{id}/mark-paid) */
  payoutsMarkPaid(id: string, input?: { "reference"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payouts/${encodeURIComponent(id)}/mark-paid`, query, all);
  }

  /** Update bank account (PATCH /api/v1/payouts/bank-account) */
  payoutsUpdateBankAccount(input: { "bankCode"?: string; "bankName": string; "bankAccountNumber": string; "bankAccountHolder": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payouts/bank-account`, query, all);
  }

  /** Archive a plan (POST /api/v1/plans/{id}/archive) */
  plansArchive(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/plans/${encodeURIComponent(id)}/archive`, query, all);
  }

  /** Create a plan (POST /api/v1/plans) */
  plansCreate(input: { "name": string; "description"?: string; "interval": "day" | "week" | "month" | "year"; "intervalCount"?: number; "trialDays"?: number; "portalFeatures": Record<string, unknown>; "dunningPolicyId"?: string; "usageAggregate"?: "sum" | "max" | "last"; "meteredUnit"?: string; "active"?: boolean; "metadata"?: Record<string, unknown>; "prices": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/plans`, query, all);
  }

  /** Get a plan (GET /api/v1/plans/{id}) */
  plansGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/plans/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List plans (GET /api/v1/plans) */
  plansList(input?: { "active"?: unknown; "cursor"?: unknown; "limit"?: unknown; "order"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["active"] = all["active"]; delete all["active"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    return this.call("GET", `/api/v1/plans`, query, undefined);
  }

  /** Prices a plan (POST /api/v1/plans/{id}/prices) */
  plansPrices(id: string, input: { "currency": string; "model": "flat" | "tiered" | "volume" | "usage"; "unitAmount"?: number; "tiers"?: unknown[]; "taxMode"?: "inclusive" | "exclusive"; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/plans/${encodeURIComponent(id)}/prices`, query, all);
  }

  /** Update a plan (PATCH /api/v1/plans/{id}) */
  plansUpdate(id: string, input?: { "name"?: string; "description"?: string; "trialDays"?: number; "portalFeatures"?: Record<string, unknown>; "dunningPolicyId"?: string; "active"?: boolean; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/plans/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a portal session (POST /api/v1/portal-sessions) */
  portalSessionsCreate(input: { "customerId": string; "returnUrl": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/portal-sessions`, query, all);
  }

  /** Delete a price (DELETE /api/v1/prices/{id}) */
  pricesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/prices/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Update a price (PATCH /api/v1/prices/{id}) */
  pricesUpdate(id: string, input: { "active": boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/prices/${encodeURIComponent(id)}`, query, all);
  }

  /** Public customer-facing invoice — used by hostedInvoiceUrl. (GET /api/v1/public/checkout/invoices/{id}) */
  publicCheckoutInvoices(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/checkout/invoices/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Canonical public receipt page: /r/:receiptId. (GET /api/v1/public/checkout/receipts/{id}) */
  publicCheckoutReceipts(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/checkout/receipts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a session (GET /api/v1/public/checkout/sessions/{id}) */
  publicCheckoutSessions(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/checkout/sessions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Buyer claim a session (POST /api/v1/public/checkout/sessions/{id}/buyer-claim) */
  publicCheckoutSessionsBuyerClaim(id: string, input?: { "proofUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/checkout/sessions/${encodeURIComponent(id)}/buyer-claim`, query, all);
  }

  /** Charge a session (POST /api/v1/public/checkout/sessions/{id}/charge) */
  publicCheckoutSessionsCharge(id: string, input: { "method": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/checkout/sessions/${encodeURIComponent(id)}/charge`, query, all);
  }

  /** Proof image a session (POST /api/v1/public/checkout/sessions/{id}/proof-image) */
  publicCheckoutSessionsProofImage(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/public/checkout/sessions/${encodeURIComponent(id)}/proof-image`, {}, undefined);
  }

  /** Public customer-facing receipt by session id. (GET /api/v1/public/checkout/sessions/{id}/receipt) */
  publicCheckoutSessionsReceipt(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/checkout/sessions/${encodeURIComponent(id)}/receipt`, {}, undefined);
  }

  /** Email a receipt (POST /api/v1/receipts/{id}/email) */
  receiptsEmail(id: string, input?: { "to"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/receipts/${encodeURIComponent(id)}/email`, query, all);
  }

  /** Get a receipt (GET /api/v1/receipts/{id}) */
  receiptsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/receipts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List receipts (GET /api/v1/receipts) */
  receiptsList(input?: { "cursor"?: unknown; "customerId"?: unknown; "issuedAfter"?: unknown; "issuedBefore"?: unknown; "limit"?: unknown; "sourceType"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["issuedAfter"] = all["issuedAfter"]; delete all["issuedAfter"];
    query["issuedBefore"] = all["issuedBefore"]; delete all["issuedBefore"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["sourceType"] = all["sourceType"]; delete all["sourceType"];
    return this.call("GET", `/api/v1/receipts`, query, undefined);
  }

  /** List receipt.escpos (GET /api/v1/receipts/{id}/receipt.escpos) */
  receiptsReceiptEscpos(id: string, input?: { "width"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["width"] = all["width"]; delete all["width"];
    return this.call("GET", `/api/v1/receipts/${encodeURIComponent(id)}/receipt.escpos`, query, undefined);
  }

  /** List receipt.html (GET /api/v1/receipts/{id}/receipt.html) */
  receiptsReceiptHtml(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/receipts/${encodeURIComponent(id)}/receipt.html`, {}, undefined);
  }

  /** List receipt.pdf (GET /api/v1/receipts/{id}/receipt.pdf) */
  receiptsReceiptPdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/receipts/${encodeURIComponent(id)}/receipt.pdf`, {}, undefined);
  }

  /** Create a refund (POST /api/v1/refunds) */
  refundsCreate(input?: { "chargeId"?: string; "sourceType"?: "checkout_session" | "invoice"; "sourceId"?: string; "amount"?: number; "reason"?: "duplicate" | "fraudulent" | "requested_by_customer" | "other"; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/refunds`, query, all);
  }

  /** Get a refund (GET /api/v1/refunds/{id}) */
  refundsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/refunds/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List refunds (GET /api/v1/refunds) */
  refundsList(input?: { "chargeId"?: unknown; "cursor"?: unknown; "limit"?: unknown; "order"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["chargeId"] = all["chargeId"]; delete all["chargeId"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/refunds`, query, undefined);
  }

  /** List cash flow (GET /api/v1/reports/cash-flow) */
  reportsCashFlow(): Promise<unknown> {
    return this.call("GET", `/api/v1/reports/cash-flow`, {}, undefined);
  }

  /** CSV export — streamed as text/csv attachment. (GET /api/v1/reports/ledger.csv) */
  reportsLedgerCsv(): Promise<unknown> {
    return this.call("GET", `/api/v1/reports/ledger.csv`, {}, undefined);
  }

  /** List pnl (GET /api/v1/reports/pnl) */
  reportsPnl(): Promise<unknown> {
    return this.call("GET", `/api/v1/reports/pnl`, {}, undefined);
  }

  /** Cancel a subscription (POST /api/v1/subscriptions/{id}/cancel) */
  subscriptionsCancel(id: string, input: { "at": "now" | "period_end"; "reason"?: "customer_portal" | "merchant" | "failed_payment" | "user_request"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/subscriptions/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Create a subscription (POST /api/v1/subscriptions) */
  subscriptionsCreate(input: { "customerId": string; "planId": string; "priceId": string; "trialDays"?: number; "paymentTokenId"?: string; "collectionMethod"?: "charge_automatically" | "send_invoice"; "couponId"?: string; "startAt"?: string; "metadata"?: Record<string, unknown>; "initialDiscount"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/subscriptions`, query, all);
  }

  /** Get a subscription (GET /api/v1/subscriptions/{id}) */
  subscriptionsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List subscriptions (GET /api/v1/subscriptions) */
  subscriptionsList(input?: { "cursor"?: unknown; "customerId"?: unknown; "limit"?: unknown; "order"?: unknown; "planId"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["planId"] = all["planId"]; delete all["planId"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/subscriptions`, query, undefined);
  }

  /** Pause a subscription (POST /api/v1/subscriptions/{id}/pause) */
  subscriptionsPause(id: string, input?: { "resumeAt"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/subscriptions/${encodeURIComponent(id)}/pause`, query, all);
  }

  /** Resume a subscription (POST /api/v1/subscriptions/{id}/resume) */
  subscriptionsResume(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/subscriptions/${encodeURIComponent(id)}/resume`, query, all);
  }

  /** Update a subscription (PATCH /api/v1/subscriptions/{id}) */
  subscriptionsUpdate(id: string, input?: { "priceId"?: string; "defaultPaymentTokenId"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/subscriptions/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a template (POST /api/v1/templates) */
  templatesCreate(input?: { "kind"?: "receipt" | "invoice" | "checkout"; "name"?: string; "isDefault"?: boolean; "config"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/templates`, query, all);
  }

  /** Delete a template (DELETE /api/v1/templates/{id}) */
  templatesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/templates/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Duplicate a template (POST /api/v1/templates/{id}/duplicate) */
  templatesDuplicate(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/templates/${encodeURIComponent(id)}/duplicate`, {}, undefined);
  }

  /** Get a template (GET /api/v1/templates/{id}) */
  templatesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/templates/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List templates (GET /api/v1/templates) */
  templatesList(input?: { "kind"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["kind"] = all["kind"]; delete all["kind"];
    return this.call("GET", `/api/v1/templates`, query, undefined);
  }

  /** Make default a template (POST /api/v1/templates/{id}/make-default) */
  templatesMakeDefault(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/templates/${encodeURIComponent(id)}/make-default`, {}, undefined);
  }

  /** Create a preview (POST /api/v1/templates/preview) */
  templatesPreview(input?: { "kind"?: "receipt" | "invoice" | "checkout"; "config"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/templates/preview`, query, all);
  }

  /** Update a template (PATCH /api/v1/templates/{id}) */
  templatesUpdate(id: string, input?: { "name"?: string; "config"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/templates/${encodeURIComponent(id)}`, query, all);
  }

  /** Create an advance (POST /api/v1/test/clocks/advance) */
  testClocksAdvance(input: { "subscriptionId": string; "days": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/test/clocks/advance`, query, all);
  }

  /** Create an image (POST /api/v1/uploads/image) */
  uploadsImage(): Promise<unknown> {
    return this.call("POST", `/api/v1/uploads/image`, {}, undefined);
  }

  /** Create a webhook (POST /api/v1/webhooks) */
  webhooksCreate(input?: { "description"?: unknown; "events"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhooks`, query, all);
  }

  /** Delete a webhook (DELETE /api/v1/webhooks/{id}) */
  webhooksDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhooks/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List webhooks (GET /api/v1/webhooks) */
  webhooksList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks`, {}, undefined);
  }

  /** Url / events / active / description. (PATCH /api/v1/webhooks/{id}) */
  webhooksUpdate(id: string, input?: { "active"?: unknown; "description"?: unknown; "events"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhooks/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a workspace (POST /api/v1/workspaces) */
  workspacesCreate(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/workspaces`, query, all);
  }

  /** Delete a workspace (DELETE /api/v1/workspaces/{id}) */
  workspacesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/workspaces/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List workspaces (GET /api/v1/workspaces) */
  workspacesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/workspaces`, {}, undefined);
  }

  /** Update a workspace (PATCH /api/v1/workspaces/{id}) */
  workspacesUpdate(id: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/workspaces/${encodeURIComponent(id)}`, query, all);
  }
}
